### ISSUE TITLE
fatal: unable to access 'https://github.com/Ash258/Scoop-Core/': Unsupported proxy syntax in '127.0.0.1:8080 '

### ISSUE THREAD

**Issue by linsui** [Ash258/Scoop-Core#124]
- **Branch**:  Master
- **Powershell Version**:  5.1.19041.610

I set proxy to 127.0.0.1:8080 which works well with scoop but got this error with shovel
```
Updating Scoop...
fatal: unable to access 'https://github.com/Ash258/Scoop-Core/': Unsupported proxy syntax in '127.0.0.1:8080 '
```

```
scoop config proxy 127.0.0.1:8080
scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/Ash258/Scoop-Core/': Unsupported proxy syntax in '127.0.0.1:8080 '
```

I'm using a proxy.

**Comment by Ash258** [comment]
Proxy handling is same as in scoop. I am not going to do anything about proxy configuration

Use proxifier or something similar. Application specific proxies does not make sense.

**Comment by linsui** [comment]
Weird, yesterday I switched to shovel and the proxy setting doesn't work anymore today.

Ok, I dig into it and find the error.

https://github.com/Ash258/Scoop-Core/blob/e342149253629eb52591083dbb149c86ea96784b/lib/Git.ps1#L65

The spaces in the command cause the error. Remove them and everything works again.

**Comment by linsui** [comment]
Will you fix it?

**Comment by Ash258** [comment]
2 months to master
Few days to NEW

**Comment by linsui** [comment]
Thanks!
