### ISSUE TITLE
ERROR Shovel flavour of scoop is required. 

### ISSUE THREAD

**Issue by digrouz** [Ash258/Scoop-Core#130]
- **Branch**: master
- **Powershell Version**: 5.1.19041.868

While installing some stuff from your own bucket like speccy or Totalcommander, i get an error: ERROR Shovel flavour of scoop is required. 

d:\> scoop install speccy
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'speccy' (1.32.744) [64bit]
Loading spsetup132.exe from cache.
Loading sp.dll from cache.
Loading sp.dat from cache.
Checking hash of spsetup132.exe ... ok.
Checking hash of sp.dll ... ok.
Checking hash of sp.dat ... ok.
Extracting cosi.7z ... done.
Running pre-install script...
ERROR Shovel flavour of scoop is required

Also since a few days, a "scoop list" return all my installed software as failed. Can you help ?

**Comment by Ash258** [comment]
You clearly have vanilla scoop installed

**Comment by digrouz** [comment]
> cat  ~/.config/scoop/config.json
{
    "lastupdate":  "2021-03-21T23:33:53.0012237+01:00",
    "SCOOP_REPO":  "https://github.com/Ash258/Scoop-Core",
    "SCOOP_BRANCH":  "master",
    "MSIEXTRACT_USE_LESSMSI":  true,
    "aria2-enabled":  false
}

**Comment by Ash258** [comment]
`git -C "$env:SCOOP\apps\scoop\current" remote -vv` `shovel update`

**Comment by digrouz** [comment]
```
git -C "$env:SCOOP\apps\scoop\current" remote -vv
origin  https://github.com/Ash258/Scoop-Core (fetch)
origin  https://github.com/Ash258/Scoop-Core (push)
```

shovel update fails, i've not shovel command on my system, isn't still scoop the name of the command?

**Comment by Ash258** [comment]
```
git -C "$env:SCOOP\apps\scoop\current" status
git -C "$env:SCOOP\apps\scoop\current" fetch --all --prune
git -C "$env:SCOOP\apps\scoop\current" checkout main
git -C "$env:SCOOP\apps\scoop\current" pull
```

**Comment by digrouz** [comment]
this fixed it: `git -C "$env:SCOOP\apps\scoop\current" reset --hard`

The git status showed a lot of modified files that I never touched. Might it be because I issued by error a scoop update from a WSL shell ?
