### ISSUE TITLE
Hightlight leak

### ISSUE THREAD

**Issue by linsui** [Ash258/Scoop-Core#138]
- **Branch**: NEW
- **Powershell Version**: 5.1.19041.610

Hightlight leak

![sshot-009](https://user-images.githubusercontent.com/36977733/114142272-4a45ba00-9902-11eb-8bbe-20e329959287.png)

**Comment by Ash258** [comment]
Not a scoop/Shovel bug. Can repro in vanilla scoop. This comes from Python installer itself when installing pip.

Fixed in the manifest in ScoopInstaller/Main@f8b2604536d7f0ac6d585577e518ef097c7bfcff
