### ISSUE TITLE
When using NO_JUNCTIONS config, helpers like dark or lessmsi are not found

### ISSUE THREAD

**Issue by dwettstein** [Ash258/Scoop-Core#146]
- **Branch**: master
- **Powershell Version**: 5.1.19041.906

The `NO_JUNCTIONS` config can be used if users don't want or cannot use the `current` symlinks.

> NO_JUNCTIONS: $true|$false
>   The 'Current' version alias will not be used.
>   Shims and shortcuts will point to specific version instead.

Unfortunately, when this setting is set to `true`, Scoop doesn't find decompression helpers like _dark_ or _lessmsi_ anymore. Reason is, the method `Get-AppFilePath` used by `Get-HelperPath` searches for a hard-coded path `current`.

https://github.com/Ash258/Scoop-Core/blob/4fb735c7afd867b2bcf6619a38dcddaaa2cadc31/lib/core.ps1#L314
at https://github.com/Ash258/Scoop-Core/blob/4fb735c7afd867b2bcf6619a38dcddaaa2cadc31/lib/core.ps1#L294
at https://github.com/Ash258/Scoop-Core/blob/4fb735c7afd867b2bcf6619a38dcddaaa2cadc31/lib/core.ps1#L339

Eventually this could be fixed, if Scoop would use the shims instead of looking at `current` path?

Relates: https://github.com/lukesampson/scoop/issues/4350

**Comment by Ash258** [comment]
For what reason do you duplicate issues??
