### ISSUE TITLE
If I uninstall git, leave it alone, and then try to install it again, it fails.

### ISSUE THREAD

**Issue by yuusakuri** [Ash258/Scoop-Core#167]
- **main**: 
- **5.1.19041.906**: 

## environment
![env](https://user-images.githubusercontent.com/58417213/121368745-42dc7480-c976-11eb-8df9-a5058e9d9891.PNG)

## error
`scoop install git` fails
![error](https://user-images.githubusercontent.com/58417213/121368766-47a12880-c976-11eb-9604-756d7261ed5c.PNG)

## Step

1. Install base scoop
2. Add some scoop buckets
3. Install some scoop apps
4. Change the scoop repository to this repository
5. Uninstall git and leave it for a few days
6. Attempting to install git again fails

**Comment by Ash258** [comment]
`shovel config lastupdate 258|2021-06-09 17:23:01`

**Comment by yuusakuri** [comment]
Thank you very much.
