### ISSUE TITLE
Shows application old version as available update

### ISSUE THREAD

**Issue by kekdev** [Ash258/Scoop-Core#195]
- **Branch**: main
- **Powershell Version**: 7.1.4

Don't know is it normal behavior?
If it depends on changes in bucket maybe it needs to be marked as rolled back to older version

![image](https://user-images.githubusercontent.com/6170034/130372356-27e99f61-aaf7-4cde-bfab-2b94d548e6a4.png)

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/130390027-008107fe-dee5-4cd2-9dca-8062aaec06c6.png)

**Comment by kekdev** [comment]
It's updated to older version in bucket

https://github.com/lukesampson/scoop-extras/commit/8a4bcfe95e1fab8b688dc48dfd1e941610da12fa
