### ISSUE TITLE
shovel commands do not work well with pipeline chain operator '&&' in powershell core

### ISSUE THREAD

**Issue by LoZeno** [Ash258/Scoop-Core#196]
- **Branch**: main

- **Powershell Version**: 7.1.4

When chaining shovel commands with other applications using the pipeline chain operator &&, shovel interrupts the pipeline.
E.G., running "shovel status" shows three updates today; running "choco outdated" gives me two updates of apps I installed with it.  
If I run 'choco outdated && shovel status', I get the list of updates from both applications; but if I invert the order, e.g. 'shovel status && choco outdated' only shovel's output is presented, the pipeline does not run the choco command.

The issue is not present when using Luke Sampson's original scoop branch.

shovel status:
![image](https://user-images.githubusercontent.com/3267561/130412934-e1f059dc-47de-4acc-ba80-9102138d6898.png)
choco outdated:
![image](https://user-images.githubusercontent.com/3267561/130412973-9f3196f5-4b95-4bdf-80f0-3382ce7cac71.png)
chaining shovel after choco outdated:
![image](https://user-images.githubusercontent.com/3267561/130413040-b81db303-976b-48ac-85bf-db5355b62a79.png)
chaining choco AFTER shovel (shows the issue):
![image](https://user-images.githubusercontent.com/3267561/130413088-a8fe9f92-2f7c-4eaf-acb2-61f94dff2860.png)
chaining ANY powershell commandlet after shovel status:
![image](https://user-images.githubusercontent.com/3267561/130413311-6ae3ee50-4eeb-4d7a-9c59-29b5b0f6a70f.png)

**Comment by Ash258** [comment]
Work as expected.

https://github.com/Ash258/Scoop-Core/blob/5b2dd88316c95e61dec85d1ab49d6e6e9d776ad0/libexec/scoop-status.ps1#L69-L75

`shovel status; write-host $LASTEXITCODE # Will return 3`

**Comment by LoZeno** [comment]
No it does not: the ; operator is not the && operator in powershell core.

**Comment by Ash258** [comment]
`&&` works only if the first command finished successfully. Which obviously did not, when the exit code is 3

**Comment by LoZeno** [comment]
Please clarify how the "status" command is not successful if it shows outdated apps. Isn't its purpose to show what needs updates? Why is it considered a failure?

**Comment by Ash258** [comment]
> Isn't its purpose to show what needs updates?

Completely irrelevant question, which could be solved as easy as run `shovel help status` or `shovel status --help`

Why should it be a success?

Exposing yourself to non-patched version of application, allowing security threats on your system is success?

**Comment by LoZeno** [comment]
> Why should it be a success?

Because the process itself didn't fail, it successfully did what it was set out to do.

> Completely irrelevant question, which could be solved as easy as run `shovel help status` or `shovel status --help`
That was a rhetoric question, I realise it doesn't really pass that way in a terse message.

But in short:
`❯ scoop help status
Usage: scoop status [<OPTIONS>]

Show status and check for available updates for all installed applications.`

If that's what the process does, then returning a list of applications to update without encountering errors in the process doesn't sound like it should return an error code.

**Comment by Ash258** [comment]
No. The current implementation is correct. Clear from the help entry. I agree that the original summary could be improved, but not now and not in near future.

Without the exit code status you have no way how to easily programmatically check if something is wrong. As soon as machine-readable, p, json output is in place the exit codes will be changed to unique one to easily chain other operations, based on exit code and json output.

Does not make any sense to keep it 0, just to stick with some other tool.
