### ISSUE TITLE
`shovel status` much slower than `scoop status` for large number of installed apps

### ISSUE THREAD

**Issue by david-bakin** [Ash258/Scoop-Core#204]
```
PS C:\Users\David> shovel config SCOOP_BRANCH
main
PS C:\Users\David> $PSVersionTable.PSVersion.ToString()
7.1.4
```

(shovel installed 2021-09-18, scoop was up-to-date before the upgrade mentioned below)

`shovel status` is much slower than `scoop status` on same set of 196 apps installed.  ~35s vs ~2s with hot file system cache both times.  

I saw this on a different VM, so in _this_ VM I did `scoop status` three times, ~2s each for the 2nd & 3rd try, then upgraded to shovel, restarted powershell, then did `shovel status` three times, ~35s each for the 2nd & 3rd try.  Actually the _first_ time of each scoop vs shovel run was very similar, 2s and ~35-40s.

Both in same environment, a Microsoft Windows [Version 10.0.19043.1237] running in a VM with 2cores (real not hyperthread), 10Gb RAM (flexible to 24Gb), nothing else running on this laptop _except_ this VM which was running nothing else, scoop/shovel directory `~/scoop` in the VM's VHD, not mounted remotely.

**Comment by leni8ec** [comment]
I confirm. i have the same problem on 3 different PC.
`scoop status` takes - a lot of time.

**Comment by david-bakin** [comment]
Not happening for me anymore ... the last week maybe (same machines).  Seems nice and fast.

**Comment by leni8ec** [comment]
> Not happening for me anymore ... the last week maybe (same machines). Seems nice and fast.

I confirm!  It takes several seconds (3-4) to "Scoop is up to date" and 2 seconds to show the list of updates for apps
