### ISSUE TITLE
404 error downloading with Shovel but not base Scoop

### ISSUE THREAD

**Issue by DessertArbiter** [Ash258/Scoop-Core#215]
- **Branch**: main
 
- **Powershell Version**: 7.1.5
 

Issue described [here](https://github.com/ScoopInstaller/Extras/issues/7204).
Right now, I only know about it affecting programs that download from TechPowerUp. Trying to download throws error 404 both with and without aria2. They download correctly with the base Scoop, the error is unique to Shovel. Both programs are located in the extras bucket.

<details>
<summary>With aria2</summary>

```
ERROR Download failed! (Error 3) Resource was not found
ERROR http://us2-dl.techpowerup.com/files/GPU-Z.2.43.0.exe#/GPU-Z.exe
    referer=http://us2-dl.techpowerup.com/files/GPU-Z.2.43.0.exe#/
    dir=C:\Users\tim\scoop\cache
    out=gpu-z#2.43.0#http_us2-dl.techpowerup.com_files_GPU-Z.2.43.0.exe_GPU-Z.exe

ERROR & 'C:\Users\tim\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\tim\scoop\cache\gpu-z.txt' --user-agent='Shovel/1.0 (+https://shovel.ash258.com) PowerShell/7.1 (Windows NT 10.0.19043.0; Win64; x64;)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=20276 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found
```

</details>

<details>
<summary>Without aria2</summary>

`ERROR The remote server returned an error: (404) Not Found.`

</details>

I am not using a proxy or VPN.

**Comment by Ash258** [comment]
Not gonna work. There is whitelist of useragents and Shovel one is not on it.

Will not be there either.
