### ISSUE TITLE
Microsoft Defender detects `VirTool:PowerShell/PoshC2.gen!E`- in lib/core.ps1

### ISSUE THREAD

**Issue by 42wim** [Ash258/Scoop-Core#216]
- **Branch**: main
- **Powershell Version**: 5.1.19041.1237

Scoop/shovel stops working: `This script contains malicious content and has been blocked by your antivirus software.`

![image](https://user-images.githubusercontent.com/1810977/141511440-249343d4-bf6b-4487-a3d5-56eef3b40083.png)

I've pinpointed it to the `Optimize-SecurityProtocol` function, when I remove it from the code it works again.

Related https://github.com/ScoopInstaller/Scoop/issues/4097

**Comment by Ash258** [comment]
Irrelevant. Scoop should be added as exclusion.

https://github.com/Ash258/Scoop-Core/blob/2c43379eadcd61c83995e7562fcf26a3038bfaf0/README.md?plain=1#L45
https://github.com/Ash258/Scoop-Core/blob/2c43379eadcd61c83995e7562fcf26a3038bfaf0/lib/Diagnostic.ps1#L46-L77
