### ISSUE TITLE
Embedded powershell-yaml collides with global powershell-yaml

### ISSUE THREAD

**Issue by scottbilas** [Ash258/Scoop-Core#244]
- **Branch**: main
- **Powershell Version**: 7.2.0

`Import-Module powershell-yaml`, or anything that depends on it (in my case, `unitysetup`) will fail if Shovel is installed.

```
import-module powershell-yaml
Exception: Cannot add type. The type name 'StringQuotingEmitter' already exists.
  At C:\Users\scott\Documents\PowerShell\Modules\powershell-yaml\0.4.2\powershell-yaml.psm1:312 char:5
  +     Add-Type -TypeDefinition $stringQuotingEmitterSource -ReferencedA …
  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  at C:\Users\scott\Documents\PowerShell\Modules\powershell-yaml\0.4.2\powershell-yaml.psm1: line 312

# after hacking around that..

import-module powershell-yaml
SessionStateException: The alias is not allowed, because an alias with the name 'cfy' already exists.
  At C:\Users\scott\Documents\PowerShell\Modules\powershell-yaml\0.4.2\powershell-yaml.psm1:414 char:1
  + New-Alias -Name cfy -Value ConvertFrom-Yaml
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  at C:\Users\scott\Documents\PowerShell\Modules\powershell-yaml\0.4.2\powershell-yaml.psm1: line 414
```

The module is being imported by Shovel with `-Prefix 'CloudBase'` but this only affects exported function names. Types and aliases do not get prefixed and end up with this collision.

Locally I have hacked `supporting\yaml\bin\powershell-yaml.psm1` like this:

* Rename `StringQuotingEmitter` to `ShovelStringQuotingEmitter`
* Comment-out the `cfy` and `cty` aliases at bottom

**Comment by scottbilas** [comment]
Ach, after further testing, this is a local problem I have. Sorry for the bother!

**Comment by Ash258** [comment]
As a temporary solution you can use cmd shim (`shovel.cmd <commands>`) this will spawn own powershell, which should not be affected by this.

Alternativelly adjust the cmd shim to use the version of powershell you need/expect as by default it uses powershell 5.

**Comment by scottbilas** [comment]
Thanks, but the problem was in my profile, I had an errant command that accidentally pulled in the Shovel embedded yaml psm1. Removed that and have done some more testing, appears resolved. Again, sorry for the waste of time.

Good idea about the cmd shim as a debug tool for the future though, thanks for that as well. :)
