### ISSUE TITLE
ConvertFrom-Json problem

### ISSUE THREAD

**Issue by arinoki** [Ash258/Scoop-Core#245]
```
{
  "lastupdate": "258|2021-12-16 12:42:51",
  "SCOOP_REPO": "https://github.com/Ash258/Scoop-Core",
  "SCOOP_BRANCH": "main"
}
```

Since yesterday I have such error while trying to update. 

`ConvertFrom-Json: C:\users\sora\scoop\apps\scoop\current\lib\manifest.ps1:40
Line |
  40 |  …   $result = ConvertFrom-Json -InputObject $content -ErrorAction 'Stop …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: v. Path '', line 0, position 0.`

https://i.imgur.com/NQZmnof.png

I'm using Powershell 7.2.0.101/Win 11.

**Comment by Ash258** [comment]
Do not use my personal bucket

`shovel bucket rm ash258.ash258`, `shovel bucket rm Ash258`

**Comment by arinoki** [comment]
Interesting solution, and I somehow found the problem - it was with oh-my-posh. So I removed your bucket, oh-my-posh, installed it again from Base bucket, and after added your bucket again. And seems right now everything fine.
