### ISSUE TITLE
project overview available?

### ISSUE THREAD

**Issue by david-bakin** [Ash258/Scoop-Core#65]
Is there a doc/wiki page/something that describes how Shovel improves over Scoop?  And also addresses compatibility?  I'm concerned that if I switch to the Shovel I wouldn't be able to easily go back (should it become necessary).

I'm interested in the Shovel because I see a few hints in the commits that one of the enhancements has to do with command completion - sounds useful!

**Comment by Ash258** [comment]
https://github.com/ash258/scoop-core/releases

Not backward compatible and will not be.
