### ISSUE TITLE
Move to ScoopInstaller/Core

### ISSUE THREAD

**Issue by krnd** [Ash258/Scoop-Core#92]
You seem like picking up the reins on developing scoop while the original repo is making only slow progress. Can we somehow make this the new official scoop repo and move it to **ScoopInstaller/Core** before it gets diverged? As of now this seems to be the most up-to-date scoop repo out there.

_I recently found scoop and think it got tremendous potential due to not requiring admin privileges (e.g. company internal distribution, easy personalized development environment, virtual development environments, ...).
It would be sad if the project dies._

**Comment by Ash258** [comment]
No. My fork will never be part of original scoop.

**Comment by krnd** [comment]
May I ask why?

**Comment by Ash258** [comment]
In original core are lots of incompetent people, who are requesting feature directly against scoop philosophy, and I do not want to be connected with them by any means.

Original author of scoop left far away so there is no reason to stick with it.

**Comment by Luckz** [comment]
> In original core are lots of incompetent people, who are requesting feature directly against scoop philosophy

Do you have examples of the kind of features you mean? (Just trying to understand.)

**Comment by igitur** [comment]
Urgh... ok, so I've read this thread and I understand it. Just such a pity that yet another awesome open-source framework is forked. 

But ok, going forward, can I add packages to the repos that use features that Shovel supports, but Scoop doesn't? For example, the `pre_uninstall` and `post_uninstall` properties are supported only by Shovel.

**Comment by Ash258** [comment]
No
